# the same as docker-compose.yaml, but for people who want to build the image
# and run the server on their own PC

version: "3"

services:
  database:
    image: postgres:9.5
    environment:
      POSTGRES_DB: ${POSTGRES_DATABASE}
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DATA: /var/lib/postgresql/data/pgdata
    logging:
      options:
        max-size: "10m"
        max-file: "3"
    restart: always
    read_only: true
    volumes:
      - "database:/var/lib/postgresql/data"
    tmpfs:
      - "/tmp"
      - "/run"
    networks:
      db-net:

  otree:
    build: ./
    image: otree:hft
    environment:
      DATABASE_URL: "postgres://${POSTGRES_USER}:${POSTGRES_PASSWORD}@database/${POSTGRES_DATABASE}"
      OTREE_ADMIN_PASSWORD: ${OTREE_ADMIN_PASSWORD}
      OTREE_AUTH_LEVEL: ${OTREE_AUTH_LEVEL}
      NUM_WORKERS: ${NUM_WORKERS}
    ports:
      - ${OTREE_PORT}:80
    volumes:
      - "otree-resetdb:/opt/init"
    # Uncomment for live editing
    #  - ./:/opt/otree
    restart: always
    logging:
      options:
        max-size: "10m"
        max-file: "3"
    networks:
      - db-net
      - redis-net
      - exc-net

  redis:
    image: redis
    command: "redis-server"
    logging:
      options:
        max-size: "10m"
        max-file: "3"
    restart: always
    read_only: true
    networks:
      - redis-net

  exchanges:
    build: ./exchange_server/
    image: exchanges
    environment:
      NUM_GROUPS: ${NUM_GROUPS}
    logging:
      options:
        max-size: "10m"
        max-file: "3"
    restart: always
    read_only: true
    networks:
      - exc-net

volumes:
  database:
  otree-resetdb:

networks:
  db-net:
  redis-net:
  exc-net:
