# the same as docker-compose.yaml, but for people who want to build the image
# and run the server on their own PC

version: "3"

services:
  database:
    image: postgres:9.5
    environment:
      POSTGRES_DB: ${POSTGRES_DATABASE}
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DATA: /var/lib/postgresql/data/pgdata
    logging:
      options:
        max-size: "10m"
        max-file: "3"
    restart: always
    read_only: true
    volumes:
      - "database-1:/var/lib/postgresql/data"
    tmpfs:
      - "/tmp"
      - "/run"
    networks:
      db-net:

  # database-2:
  #   image: postgres:9.5
  #   environment:
  #     POSTGRES_DB: ${POSTGRES_DATABASE}
  #     POSTGRES_USER: ${POSTGRES_USER}
  #     POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
  #     POSTGRES_DATA: /var/lib/postgresql/data/pgdata
  #   logging:
  #     options:
  #       max-size: "10m"
  #       max-file: "3"
  #   restart: always
  #   read_only: true
  #   volumes:
  #     - "database-2:/var/lib/postgresql/data"
  #   tmpfs:
  #     - "/tmp"
  #     - "/run"
  #   networks:
  #     db-net-2:


  otree:
    build: ./
    depends_on:
      - database
    image: otree:hft
    environment:
      DATABASE_URL: "postgres://${POSTGRES_USER}:${POSTGRES_PASSWORD}@database/${POSTGRES_DATABASE}"
      REDIS_INS: "redis://redis-1:6379/1"
  #    EXCHANGE_GROUP: "1"
      OTREE_ADMIN_PASSWORD: ${OTREE_ADMIN_PASSWORD}
      OTREE_AUTH_LEVEL: ${OTREE_AUTH_LEVEL}
      NUM_WORKERS: ${NUM_WORKERS}
    ports:
      - 8000:80
    volumes:
      - "otree-resetdb:/opt/init"
    # Uncomment for live editing
    #  - ./:/opt/otree
    restart: always
    logging:
      options:
        max-size: "10m"
        max-file: "3"
    networks:
      - db-net
      - redis-net

  # otree-2:
  #   build: ./
  #   depends_on:
  #     - database-2
  #   image: otree:hft
  #   environment:
  #     DATABASE_URL: "postgres://${POSTGRES_USER}:${POSTGRES_PASSWORD}@database-2/${POSTGRES_DATABASE}"
  #     REDIS_INS: "redis://redis-2:6379/1"
  # #    EXCHANGE_GROUP: "2"
  #     OTREE_ADMIN_PASSWORD: ${OTREE_ADMIN_PASSWORD}
  #     OTREE_AUTH_LEVEL: ${OTREE_AUTH_LEVEL}
  #     NUM_WORKERS: ${NUM_WORKERS}
  #   ports:
  #     - 8001:80
  #   volumes:
  #     - "otree-resetdb-2:/opt/init"
  #   # Uncomment for live editing
  #   #  - ./:/opt/otree
  #   restart: always
  #   logging:
  #     options:
  #       max-size: "10m"
  #       max-file: "3"
  #   networks:
  #     - db-net-2
  #     - redis-net-2

  redis:
    image: redis
    command: "redis-server"
    logging:
      options:
        max-size: "10m"
        max-file: "3"
    restart: always
    read_only: true
    networks:
      - redis-net

  # redis-2:
  #   image: redis
  #   command: "redis-server"
  #   logging:
  #     options:
  #       max-size: "10m"
  #       max-file: "3"
  #   restart: always
  #   read_only: true
  #   networks:
  #     - redis-net-2

volumes:
  database:
  # database-2:    
  otree-resetdb:
  # otree-resetdb-2:


networks:
  db-net:
  # db-net-2:
  redis-net:
  # redis-net-2:
  
