market:
  market-design: CDA
  matching-engine-host: "127.0.0.1"

group:
  number-of-groups: 2
  players-per-group: 3

parameters:
  fundamental-price: 100
  initial-spread: 2
  initial-endowment: 20
  speed-cost: 0.01
  session-length: 240

demo:
  number-of-players: 6

files:
  dir: session-config
  folder: "2018-07-16_1"
  investors: 
    group_1: investors_1.csv
    group_2: investors_2.csv
  jumps:
    group_1: jumps_1.csv
    group_2: jumps_2.csv




  

